#!/usr/bin/env python                                                                    
# -*- coding: UTF-8 -*-                                                                                                                                        

import os
import index

if index.new_files():
    try:
        index.generate_readme()
        print("New readme generated")
        os.system("git add README.md References/index.csv")
    except Exception as e:
        print(e)
        os.system("exit 1")
else:
    print("No new reference")
